### ISSUE TITLE
Design for markers on the map makes it difficult to access specific ones when grouped together tightly

### ISSUE THREAD

**Issue by atmcniff** [girldevelopit/gdi-website#310] opened 2015-04-12 00:24 UTC
![image](https://cloud.githubusercontent.com/assets/11324044/7103842/336eef60-e06f-11e4-85b0-fd919bb16416.png)

It's difficult, in this case, to view the locations in Bucks County due to the overlapping of the other markers, where the user has to slowly move the cursor to an area on the edge where the other two markers aren't activated.
Detection range of the cursor should be changed for the markers, and when hovering over it, it should be brought to the front.

**Comment by kstack7** [comment] 2015-04-12 00:27
Thanks for the suggestions, @atmcniff 

Could you reformat the issue to match our template? You can reference it here: #83

**Comment by kstack7** [comment] 2015-08-31 23:00
An easy fix is to resize the plot circles.

10px

![screen shot 2015-08-31 at 6 51 36 pm](https://cloud.githubusercontent.com/assets/6612770/9592585/7e1e8b66-5012-11e5-83a2-d7469687fa8e.png)

8px

![screen shot 2015-08-31 at 6 51 16 pm](https://cloud.githubusercontent.com/assets/6612770/9592587/83a471fe-5012-11e5-9887-8ee64f28a2f3.png)

**Comment by ghaida** [comment] 2015-11-10 18:40
:eyes: Does this map still exist? If not, let's close this issue :grin:

**Comment by kstack7** [comment] 2015-11-10 18:42
Ah @ghaida it's the front-page map. I changed the marker radius a while back, but must not have closed this OR thought we'd have more commentary. I'm down with closing if we are okay with how it is.

**Comment by kstack7** [comment] 2015-11-10 18:43
The problem is we're seeing more grouped chapters and the markers get swamped. Not sure if the smaller size fixed it.

**Comment by ghaida** [comment] 2015-11-10 19:45
OH, I see. LGTM as long as we're not expecting people to use this as a primary means to get to the chapter pages :thumbsup:

**Comment by kstack7** [comment] 2016-01-12 05:38
Closing this unless we get new ideas aside from the smaller dots, which are in place now.

**Closed as completed by kstack7** 2016-01-12 05:38 UTC
Labels: Help Wanted, UX/Design Needed, Dev Ops, Suggestion
